# Generated by Django 5.1.4 on 2024-12-12 09:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='user',
            field=models.ManyToManyField(related_name='enrolled_workouts', through='workouts.UserWorkout', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userworkout',
            name='progress',
            field=models.CharField(blank=True, default='Pending', max_length=100, null=True),
        ),
    ]
