# Generated by Django 5.1.4 on 2024-12-13 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workouts_user_alter_userworkout_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='workouts',
            name='status',
            field=models.CharField(default='Pending', max_length=100),
        ),
    ]
